version: '2'
services:
    {{cookiecutter.project_slug}}:
        build: .
        volumes:
            - .:/src
        ports:
            - "127.0.0.1:9090:9090"
        {%- if cookiecutter.integrations.cassandra or cookiecutter.integrations.memcache or cookiecutter.integrations.redis %}
        links:
            {%- if cookiecutter.integrations.cassandra %}
            - cassandra
            {%- endif %}
            {%- if cookiecutter.integrations.memcache %}
            - memcached
            {%- endif %}
            {%- if cookiecutter.integrations.redis %}
            - redis
            {%- endif %}
            {%- if cookiecutter.integrations.hvac %}
            - vault
            {%- endif %}
        {%- endif %}
        restart: always
{%- if cookiecutter.integrations.cassandra: %}
    cassandra:
        image: cassandra
{%- endif %}
{%- if cookiecutter.integrations.memcache: %}
    memcached:
        image: memcached
{%- endif %}
{%- if cookiecutter.integrations.redis: %}
    redis:
        image: redis
{%- endif %}
{%- if cookiecutter.integrations.hvac: %}
    vault:
        image: vault:0.7.3
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: 'b4c6f298-3f80-11e7-8b88-5254001e7ad3'
            SKIP_SETCAP: '1'
{%- endif %}
